project:
  type: website

website:
  title: "Resources for DSAN Students<br>Prof. Jeff <span class='subtitle'><a href='mailto:jj1088@georgetown.edu'><i class='bi bi-envelope-at ps-1'></i></a></span>"
  sidebar:
    contents:
      - href: index.qmd
        text: "<i class='bi bi-house pe-1'></i>Home"

format:
  html:
    theme: cosmo
    css: styles.css



